//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OmniWatcher.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Channel
    {
        public byte ID { get; set; }
        public string Code { get; set; }
        public string Descrip { get; set; }
        public string PasswordHash { get; set; }
        public string AuthenticationClass { get; set; }
        public string SessionClass { get; set; }
        public byte SessionTimeout { get; set; }
        public bool AutoRegister { get; set; }
        public bool MultiSession { get; set; }
    }
}
