//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OmniWatcher.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChannelIdentitySession
    {
        public int ID { get; set; }
        public byte ChannelID { get; set; }
        public string RefNum { get; set; }
        public System.Guid SessionKey { get; set; }
        public Nullable<int> ForeignID { get; set; }
        public System.DateTime InsertDate { get; set; }
        public System.DateTime LastActiveDate { get; set; }
    }
}
