//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OmniWatcher.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class dm_client_activity_online
    {
        public int session_id { get; set; }
        public string channel { get; set; }
        public string client { get; set; }
        public string ident { get; set; }
        public string branch { get; set; }
        public string @operator { get; set; }
        public string duration { get; set; }
        public Nullable<int> client_employee { get; set; }
        public System.DateTime last_active_date { get; set; }
    }
}
